### ISSUE TITLE
npm install throws an error

### ISSUE THREAD

**Issue by Nosthertus** [JaspervRijbroek/raddish#227]
on installing raddish by following the tutorial on the website, the npm throws an error
```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\darkf\Documents\nodejs test\radish\node_modules\usage
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN EPEERINVALID mongodb-core@1.2.24 requires a peer of kerberos@~0.0 but none was installed.
npm WARN EPACKAGEJSON radish@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! usage@0.7.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usage@0.7.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the usage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usage
npm ERR! There is likely additional logging output above.
```

**Comment by JaspervRijbroek** [comment]
Hi @Nosthertus,

As far as I can see is that python isn't installed, could you confirm that python is installed by running ```python -V``` command in CMD?

Kind Regards thanks in advance

Jasper van Rijbroek

**Comment by Nosthertus** [comment]
it is not installed, i thought this was necessary, because i can't get the framework run

**Comment by JaspervRijbroek** [comment]
Unfortunately this dependency is needed at the moment, however there are plans to remove these dependencies in the future.

**Comment by JaspervRijbroek** [comment]
Is this still a present issue?
